<?php
namespace Tfg\JadBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tfg\JadBundle\Entity\JadUsuarioRol;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JadUsuarioRolRepository extends EntityRepository
{
	public function findJadsDeUsuario($usuario){
		
		   $em = $this->getEntityManager();
           $consulta = $em->createQuery('SELECT r, u FROM JadBundle:JadUsuarioRol r
   										 JOIN r.usuario u WHERE u = :id');
           $consulta->setParameter('id', $usuario);
           return $consulta->getResult();
	}
}
?>
