<?php

namespace Tfg\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function findPasswordUserbyEmail($email){
        $em = $this->getEntityManager();
        
        $dql= 'SELECT u.password password
               FROM UsuarioBundle:Usuario u
               WHERE u.email = :mail';
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('mail', $email);
        $consulta->setMaxResults(1);
        
        return $consulta->getSingleResult();
    }
}
?>
