usuario_registro:
       pattern:  /registro
       defaults: { _controller: UsuarioBundle:Default:registro }
usuario_login_check:
       pattern:   /login_check
usuario_logout:
       pattern:   /logout
home_usuario:
       pattern: /home
       defaults: { _controller: UsuarioBundle:Default:home }
crear_jad:
       pattern:  /nuevojad
       defaults: { _controller: UsuarioBundle:Default:nuevojad }